flasknews/routes.py
from flask import Blueprint, render_template, url_for, session, redirect, request
from flasknews import db, oauth, env
from flasknews.models import User, Post, UserPostAction, Comment
from urllib.parse import urlencode, quote_plus
from flask import jsonify
import json

routes = Blueprint('routes', __name__)

with open('/etc/config.json') as config_file:
    config = json.load(config_file)

# functon for displaying admin tab when user is an admin
def is_administator():
    is_admin = False
    user_id = session.get('profile', {}).get('user_id')
    if user_id:
        user = User.query.filter_by(auth0_id=user_id).first()
        if user and user.is_admin:
            is_admin = True

    return is_admin

#function to get user comments
def all_comments():
    return Comment.query.all()

# ----------------------- Auth0 integration --------------------
# Route for the auth0 callback page
@routes.route("/callback", methods=["GET", "POST"])
def callback():
    try:
        # Exchange the authorization code for an access token
        token = oauth.auth0.authorize_access_token()
        # Get the user's profile information
        userinfo_endpoint = f"https://{config['AUTH0_DOMAIN']}/userinfo"
        resp = oauth.auth0.get(userinfo_endpoint)
        userinfo = resp.json()

        # Store the user information in flask session
        session["jwt_payload"] = userinfo
        session["profile"] = {
                "user_id": userinfo["sub"],
                "name": userinfo["name"],
                "picture": userinfo["picture"],
                "email": userinfo.get("email")
                }

        # Get or create user in the database
        user = User.query.filter_by(auth0_id=userinfo["sub"]).first()
        if not user:
            # Create a new user object
            new_user = User(
                    auth0_id=userinfo["sub"],
                    username=userinfo["name"],  
                    email=userinfo["email"]
                    )
            db.session.add(new_user)
            try:
                db.session.commit()
            except Exception as e:
                print(f"Error adding user to database: {e}")
                db.session.rollback()

        return redirect('/news')
    except Exception as e:
        print(e)
        return redirect('/news')

# Route for the Login page
@routes.route('/login', methods=['GET', 'POST'])
def login():
    return oauth.auth0.authorize_redirect(
            redirect_uri=url_for("routes.callback", _external=True)
            )

# logout route for auth0
@routes.route("/logout")
def logout():
    session.clear()
    return redirect(
            "https://" + config["AUTH0_DOMAIN"]
            + "/v2/logout?"
            + urlencode(
                {
                    "returnTo": url_for("routes.home", _external=True),
                    "client_id": config["AUTH0_CLIENT_ID"],
                    },
                quote_via=quote_plus,
                )
            )

#------------------- Admin view --------------------------------

@routes.route('/admin')
def admin():
    user_id = session.get('profile').get('user_id')
    user = User.query.filter_by(auth0_id=user_id).first()
    if not user or not user.is_admin:  
        return "Access Denied", 403

    # Fetch all news items that have been liked or disliked
    news_items = Post.query.join(UserPostAction, Post.id == UserPostAction.post_id).group_by(Post.id).all()

    # Prepare a dictionary to store user actions for each news item
    news_items_with_user_actions = {}
    for item in news_items:
        actions = db.session.query(User.username, UserPostAction.action).join(UserPostAction, User.id == UserPostAction.user_id).filter(UserPostAction.post_id == item.id).all()
        news_items_with_user_actions[item.id] = {
                'post': item,
                'actions': actions
                }

    return render_template('admin.html', news_items=news_items_with_user_actions, is_admin=is_administator(), comments=all_comments())

# logic to delete a post in the admin view
@routes.route('/delete_post/<int:post_id>', methods=['POST'])
def delete_post(post_id):
    # Verify if the user is an admin
    user_id = session.get('profile').get('user_id')
    user = User.query.filter_by(auth0_id=user_id).first()
    if not user or not user.is_admin:
        return "Access Denied", 403

    # Find the post and its related actions
    post_to_delete = Post.query.get_or_404(post_id)
    actions_to_delete = UserPostAction.query.filter_by(post_id=post_id).all()

    # Delete related actions first
    for action in actions_to_delete:
        db.session.delete(action)

    db.session.delete(post_to_delete)
    db.session.commit()

    # Redirect to the admin page
    return redirect(url_for('routes.admin'))

# edit news posts for admin view
@routes.route('/edit_post/<int:post_id>', methods=['GET', 'POST'])
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)

    if request.method == 'POST':
        post.title = request.form['title']
        post.content = request.form['content']
        post.keywords = request.form.get('keywords', '')  
        db.session.commit()
        return redirect(url_for('routes.admin'))

    return render_template('edit_post.html', post=post) # go to edit_post route

#--------------------------- JSON newsfeed route --------------------------

@routes.route('/newsfeed', methods=['GET'])  
def api_newsfeed():
    # Fetch news items from the database and sort them by time and likes/dislikes
    news_items = Post.query.order_by(Post.time.desc(), Post.likes.desc(), Post.dislikes).limit(10).all()

    # Convert the news items to a JSON response
    data = {
            "news_items": [{
                'by': item.by,
                'descendants': item.descendants,
                'id': item.id,
                'kids': list(map(int, item.kids.split(','))) if item.kids else [],
                'score': item.score,
                'text': item.content,
                'time': int(item.time.timestamp()),
                'title': item.title,
                'type': item.type,
                'url': item.url
                } for item in news_items]
            }

    return jsonify(data)

#--------------------- Home page----------------------------

@routes.route("/")
def home():
    if 'profile' not in session:
        # If the user is not logged in, redirect them to the login page
        return redirect(url_for('routes.login'))
    return redirect(url_for('routes.newsfeed'))  # Redirect to the 'newsfeed' route


# -------------------- News page and functionality --------------------------

@routes.route('/news')
def newsfeed():
    page = request.args.get('page', 1, type=int)
    news_items_pagination = Post.query.order_by(Post.time.desc(), Post.likes.desc(), Post.dislikes).paginate(page=page, per_page=10, error_out=False)
    news_items = news_items_pagination.items

    user_id = session.get('profile', {}).get('user_id')
    # Fetch news items from the database and sort them by time and likes/dislikes
    news_items = (
            Post.query.order_by(Post.time.desc(), Post.likes.desc(), Post.dislikes)
            .paginate(page=1, per_page=10, error_out=False)
            .items
            )

    # Fetch user's actions on these posts
    user_actions = UserPostAction.query.filter_by(user_id=user_id).all()
    user_actions_map = {action.post_id: action.action for action in user_actions}

    # Add user-specific like/dislike information to each news item
    for item in news_items:
        item.user_action = user_actions_map.get(item.id, None)


    return render_template('newsfeed.html', news_items=news_items, pagination=news_items_pagination, comments=all_comments(), is_admin=is_administator())

# ----------------------- likes/dislikes -------------------
# logic to like a news post
@routes.route('/like/<int:post_id>')
def like(post_id):
    user_id = session.get('profile').get('user_id')
    user_name = session.get('profile').get('name')
    action = UserPostAction.query.filter_by(user_id=user_id, post_id=post_id, user_name=user_name).first()

    if action:
        if action.action == 'like':
            # User already liked, so undo the like
            db.session.delete(action)
            Post.query.get(post_id).likes -= 1
        else:
            # User had disliked, now likes
            action.action = 'like'
            Post.query.get(post_id).likes += 1
            Post.query.get(post_id).dislikes -= 1
    else:
        # New like
        new_action = UserPostAction(user_id=user_id, post_id=post_id, action='like', user_name=user_name)
        db.session.add(new_action)
        Post.query.get(post_id).likes += 1

    db.session.commit()
    return redirect(url_for('routes.newsfeed'))


# logic to dislike a news post
@routes.route('/dislike/<int:post_id>')
def dislike(post_id):
    user_id = session.get('profile').get('user_id')
    user_name = session.get('profile').get('name')
    action = UserPostAction.query.filter_by(user_id=user_id, post_id=post_id, user_name=user_name).first()

    if action:
        if action.action == 'dislike':
            # User already liked, so undo the like
            db.session.delete(action)
            Post.query.get(post_id).dislikes -= 1
        else:
            # User had disliked, now likes
            action.action = 'dislike'
            Post.query.get(post_id).dislikes += 1
            Post.query.get(post_id).likes -= 1
    else:
        # New like
        new_action = UserPostAction(user_id=user_id, post_id=post_id, action='dislike', user_name=user_name)
        db.session.add(new_action)
        Post.query.get(post_id).dislikes += 1

    db.session.commit()
    return redirect(url_for('routes.newsfeed'))

#------------------- pages for admin to view user likes/dislikes -------------------------
@routes.route('/post/<int:post_id>/likes_details')
def post_likes_details(post_id):

flasknews/templates/admin.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1>Admin Panel</h1>
    <p>Welcome, Admin! You can manage news items and users here.</p>
    <div class="news-items">
        {% for post_id, details in news_items.items() %}
        <article class="media content-section">
            <div class="media-body">
              <div class="article-metadata">
                <small class="text-muted">{{ details.post.time.strftime('%Y-%m-%d %H:%M:%S') }}</small>
              </div>
              <h2><a class="article-title" href="#">{{ details.post.title }}</a></h2>
              <p class="article-content">{{ details.post.content }}</p>
              <p>Keywords: {{ details.post.keywords }}</p>
              <span>Likes: {{ details.post.likes }}
                <a href="{{ url_for('routes.post_likes_details', post_id=details.post.id) }}">View</a>
            </span>
            <span>Dislikes: {{ details.post.dislikes }}
                <a href="{{ url_for('routes.post_dislikes_details', post_id=details.post.id) }}">View</a>
            </span>
               <!-- Action Buttons -->
               <div class="action-buttons">
                <!-- Edit Button -->
                <a href="{{ url_for('routes.edit_post', post_id=details.post.id) }}" class="btn btn-secondary">Edit</a>
                <!-- Delete Button Inside Form -->
                <form action="{{ url_for('routes.delete_post', post_id=details.post.id) }}" method="POST" style="display: inline-block;">
                    <button type="submit" class="btn btn-danger delete-button">Delete</button>
                </form>
            </div>            
          </div>
          </article>
        {% endfor %}
    </div>
</div>
{% endblock %}

flasknews/templates/dislikes_details.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1>Dislikes for Post ID: {{ post_id }}</h1>
    <ul>
        {% for user in users %}
            <li>{{ user.user_name }}: {{ user.user_id }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

flasknews/templates/edit_post.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1>Edit News Post</h1>
    <form method="POST">
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" name="title" value="{{ post.title }}">
        </div>
        <div class="form-group">
            <label for="content">Content</label>
            <textarea class="form-control" name="content">{{ post.content }}</textarea>
        </div>
        <div class="form-group">
            <label for="keywords">Keywords</label>
            <input type="text" class="form-control" name="keywords" value="{{ post.keywords }}">
        </div>
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
{% endblock %}

flasknews/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>News - {{ title }}</title>
    {% else %}
        <title>News</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if session.get('profile') %}
                <a class="nav-item nav-link" href="{{ url_for('routes.profile') }}">Profile</a>
                {% if is_admin %}
                <a class="nav-item nav-link" href="{{ url_for('routes.admin') }}">Admin</a>
                {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('routes.logout') }}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('routes.login') }}">Login</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Comments</h3>
          <form action="/post_comment" method="post">
            <textarea name="comment" class="form-control"></textarea>
            <button type="submit" class="btn btn-primary mt-2 custom-button">Post Comment</button>
          </form>
          <div class="comments-section" style="height: 300px; overflow-y: scroll;">
            {% for comment in comments %}
                <div class="comment">
                  <p class="comment-text"><strong>{{ comment.username }}:</strong> {{ comment.text }}</p>
                </div>
            {% endfor %}
        </div>
            </div>
          </div>
        </div>
      </main>

   <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
   <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj...Kk8gk=" crossorigin="anonymous"></script>
</body>
</html>

flasknews/templates/likes_details.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1>Likes for Post ID: {{ post_id }}</h1>
    <ul>
        {% for user in users %}
            <li>{{ user.user_name }}: {{ user.user_id }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

flasknews/templates/newsfeed.html
{% extends "layout.html" %}
{% block content %}
    <h1>News Feed</h1>
    <div class="news-items">
        {% for news_item in news_items %}
        <article class="media content-section">
            <div class="media-body">
              <div class="article-metadata">
                <small class="text-muted">{{ news_item.time.strftime('%Y-%m-%d %H:%M:%S') }}</small>
              </div>
              <h2><a class="article-title" href="#">{{ news_item.title }}</a></h2>
              <p class="article-content">{{ news_item.content }}</p>
              <!-- Add Like and Dislike buttons -->
              <a href="{{ url_for('routes.like', post_id=news_item.id) }}" class="btn btn-sm {{ 'btn-primary' if news_item.user_action == 'like' else 'btn-like' }}">Like</a>
              <a href="{{ url_for('routes.dislike', post_id=news_item.id) }}" class="btn btn-sm {{ 'btn-primary' if news_item.user_action == 'dislike' else 'btn-dislike' }}">Dislike</a>
              <span>Likes: {{ news_item.likes }}</span>
              <span>Dislikes: {{ news_item.dislikes }}</span>
            </div>
          </article>
        {% endfor %}
    </div>

    <!-- Pagination Controls -->
    <nav aria-label="Newsfeed pagination">
      <ul class="pagination">
          <li class="page-item {{ 'disabled' if not pagination.has_prev }}">
              <a class="page-link" href="{{ url_for('routes.newsfeed', page=pagination.prev_num) }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
              </a>
          </li>
          {% for page in pagination.iter_pages() %}
              {% if page %}
                  {% if page != pagination.page %}
                      <li class="page-item"><a class="page-link" href="{{ url_for('routes.newsfeed', page=page) }}">{{ page }}</a></li>
                  {% else %}
                      <li class="page-item active"><span class="page-link">{{ page }}</span></li>
                  {% endif %}
              {% else %}
                  <li class="page-item disabled"><span class="page-link">...</span></li>
              {% endif %}
          {% endfor %}
          <li class="page-item {{ 'disabled' if not pagination.has_next }}">
              <a class="page-link" href="{{ url_for('routes.newsfeed', page=pagination.next_num) }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
              </a>
          </li>
      </ul>
  </nav>
  
{% endblock %}

flasknews/templates/profile.html
{% extends "layout.html" %}
{% block content %}
<div class="user-profile">
  <h1>User Profile</h1>
  <div class="user-info">
    {% if session.get('profile') %}
    <div class="profile-box">
    <h3>{{ session['profile'].get('name') }}</h3>
    <p>{{ session['profile'].get('email') }}</p>
  </div>
  <div class="liked-posts">
    <!-- Display user likes and dislikes-->
    <h2>Liked Posts</h2>
    {% for action in liked_posts %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <small class="text-muted">{{ action.post.time.strftime('%Y-%m-%d %H:%M:%S') }}</small>
        </div>
        <h2><a class="article-title" href="#">{{ action.post.title }}</a></h2>
        <p class="article-content">{{ action.post.content }}</p>
        <span>Likes: {{ action.post.likes }}</span>
        <span>Dislikes: {{ action.post.dislikes }}</span>
        <a href="{{ url_for('routes.like', post_id=action.post.id) }}"
          class="btn btn-sm {{ 'btn-primary' if action.post.user_action == 'like' else 'btn-like' }}">Like</a>
        <a href="{{ url_for('routes.dislike', post_id=action.post.id) }}"
          class="btn btn-sm {{ 'btn-primary' if action.post.user_action == 'dislike' else 'btn-dislike' }}">Dislike</a>
      </div>
    </article>
    {% endfor %}
  </div>
  {% else %}
  <p>You must be logged in to view this content.</p>
  {% endif %}
</div>
</div>
{% endblock %}